require("dotenv").config();
const express = require("express");
const bridgeRoutes = require("./routes/bridgeRoute");
const connectDB = require("./config/db");
const PORT = process.env.PORT;
const app = express();
connectDB();
app.use(express.json());
app.use("/bridge", bridgeRoutes);
app.listen(PORT, () => console.log("Server started"));
